// generated by gitops_sync.task.ts - do not edit

import type { RepoJson } from '$lib/repo.svelte.ts';

import json from './repos.json' with { type: 'json' };

export const repos_json: Array<RepoJson> = json as unknown as Array<RepoJson>;
